config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :topics
  resources :networks
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/network.rb
class Network < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
end

app/models/result_status.rb
class ResultStatus < ApplicationRecord
  has_many :test_values
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :topic
  has_many :test_values
end

app/models/test_status.rb
class TestStatus < ApplicationRecord
  belongs_to :test_values
end

app/models/test_value.rb
class TestValue < ApplicationRecord
  belongs_to :tests
  belongs_to :result_statuses
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :tests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_action :set_network, only: [:show, :edit, :update, :destroy]

  # GET /networks
  # GET /networks.json
  def index
    @networks = Network.all
  end

  # GET /networks/1
  # GET /networks/1.json
  def show
  end

  # GET /networks/new
  def new
    @network = Network.new
    @networks = Network.all
  end

  # GET /networks/1/edit
  def edit
  end

  # POST /networks
  # POST /networks.json
  def create
    @network = Network.new(network_params)

    respond_to do |format|
      if @network.save
        format.html { redirect_to @network, notice: 'network was successfully created.' }
        format.json { render :show, status: :created, location: @network }
      else
        format.html { render :new }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /networks/1
  # PATCH/PUT /networks/1.json
  def update
    respond_to do |format|
      if @network.update(network_params)
        format.html { redirect_to @network, notice: 'network was successfully updated.' }
        format.json { render :show, status: :ok, location: @network }
      else
        format.html { render :edit }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /networks/1
  # DELETE /networks/1.json
  def destroy
    @network.destroy
    respond_to do |format|
      format.html { redirect_to networks_url, notice: 'network was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network
      @network = Network.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_params
      params.require(:network).permit(:name, :criteria, :network_id, :orderid)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
    @topics = Topic.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
    @topics = Topic.all
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
      @tests = Test.all
      @topics = Topic.all
      @test_values = TestValue.all
      @result_statuses = ResultStatus.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:name, :criteria, :topic_id, :orderid)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
    @topics = Topic.all
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :criteria, :topic_id, :orderid)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buildreview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/networks/edit.html.erb
<%= form_for(@network) do |f| %>
  <% if @network.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(network.errors.count, "error") %> prohibited this network from being saved:</h2>

      <ul>
      <% network.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Name: <%=@network.name%>
  </div>

  <div class="field">
    <%= f.label :android %>
    <%= f.check_box :android %>
  </div>

  <div class="field">
    <%= f.label "iOS" %>
    <%= f.check_box :ios %>
  </div>

  <div class="field">
    <%= f.label :native %>
    <%= f.check_box :native %>
  </div>

  <div class="field">
    <%= f.label :adobe %>
    <%= f.check_box :adobe %>
  </div>

  <div class="field">
    <%= f.label :unity %>
    <%= f.check_box :unity %>
  </div>

  <div class="field">
    <%= f.label "rewarded video" %>
    <%= f.check_box :ios %>
  </div>

  <div class="field">
    <%= f.label :interstitial %>
    <%= f.check_box :interstitial %>
  </div>

  <div class="field">
    <%= f.label :banner %>
    <%= f.check_box :banner %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="field">
    Fyber: <%=@network.fyber%>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    Latest Version: <%=@network.latest_version%>
  </div>

  <div class="field">
    Earlier Versions: <%=@network.versions%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', networks_path %>

app/views/networks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Networks</h1>
<ul><% @networks.each do |network| %><br>
      <li><b><%= network.name%></b></li>
      <li>Android: <%= network.android%> iOS: <%= network.ios%></li>
      <li>native: <%= network.native%> adobe: <%= network.adobe%> unity: <%= network.unity%></li>
      <li>rewarded video: <%= network.rv%> interstitial: <%= network.interstitial%> banner: <%= network.banner%></li>
      <li>last_version: <%= network.latest_version%></li>
      <li>earlier versions: <%= network.versions%></li>
      <li>fyber: <%= network.fyber%> overall active: <%= network.active%></li>
      <li>comment: <%= network.comment%></li>
      <li>
      <%= link_to 'Edit', edit_network_path(network) %>
      <%= link_to 'Destroy', network, method: :delete, data: { confirm: 'Are you sure?' } %></li>

  <% end %></ul>

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :orderid %>
    <%= f.number_field :orderid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1>Create a new Topic</h1>
<%= render 'form', topic: @topic %>

<h1>Find all other Topics for editing below</h1>
<b>Please consider that topics are orderd by orderids<b>

<% @topics.order("orderid asc").each do |t|%>
<%= render 'form', topic: t %>
<%end %>


<%= link_to 'Back', tests_path %>